language: ruby
branches:
  only:
  - gh-pages
rvm:
- 3.2.0
install:
- rm Gemfile.lock
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  target_branch: master
  on:
    branch: gh-pages