language: ruby
rvm:
- 2.3.1
install:
- rm Gemfile.lock
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: master