# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anna Rogers
author: annargrs
email: arogers@cs.uml.edu
description: >- # this means to ignore newlines until "baseurl:"
  Anna Rogers' personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: annargrs
github_username:  annargrs
url: "https://annargrs.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "annargrs/annargrs.github.io"

# publishing from the docs folder
destination: docs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-scholar
  - jekyll-sitemap
  - jemoji

theme: minimal-mistakes-jekyll

scholar:
  # more options: https://pages.lip6.fr/Pascal.Poizat/blog/posts/2016/02/01/jekyll-and-bibtex/
  style: _bibliography/apa_modified.csl
#  style: _bibliography/springer-lecture-notes-in-computer-science.csl
  sort_by: year
  order: descending
  bibliography_template: bib
  use_raw_bibtex_entry: true # to enable {{...}} inside bibtex
#  bibliography_template: "{{ reference | replace_first: 'Gladkova, A.', '<b>Gladkova, A.</b>' | replace_first: 'Rogers, A.', '<b>Rogers, A.</b>' }}"

include: ['_pages']

#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


## default YAML for all posts
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

author:
#  name: "Anna Rogers"
  avatar: "/assets/images/aro.jpg"
#  bio: "University of Copenhagen"
#  uri: "http://www.annargrs.github.io"
  twitter: "annargrs"
  linkedin: "annargrs"
  github: "annargrs"
#  vine: "doesn't matter"
  links:
    - label: "University of Copenhagen"
      icon: "fas fa-fw fa-university"
      url: "https://research.ku.dk/search/result/?pure=en%2Fpersons%2F692025"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai"
      # ai-semantic-scholar, ai-orcid - see more at https://jpswalsh.github.io/academicons/
      url: "https://scholar.google.com/citations?user=5oCYOE0AAAAJ&hl=en"
    - label: "Semantic Scholar"
      icon: "ai ai-semantic-scholar ai"
      url: "https://www.semanticscholar.org/author/Anna-Rogers/145046059"
    - label: "ORCID"
      icon: "ai ai-orcid ai"
      url: "https://orcid.org/0000-0002-4845-4023"

# SEO and Analytics
#google_site_verification : "todo"
#bing_site_verification   : "todo"
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "UA-127096214-3"
environment: production # should work, if not check if env set to development
